version: "3.7"
services:
  pg1:
    container_name: church_postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg1_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
volumes:
  pg1_data:
