version: "3.7"
services:
  pg1:
    container_name: church_postgres
    image: postgres
    volumes:
      - pg1_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

  cache:
    image: redis:7.0.4
    restart: always
    volumes:
      - ./data/cache:/data

  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"

  web:
    build: .
    command: [
        # "bash",
        # "-c",
        # "chmod +x ./wait-for-it.sh",
        # "&&",
        "./wait-for-it.sh",
        "pg1:5432",
        "--",
        "uwsgi",
        "--ini",
        "/code/config/uwsgi/uwsgi.ini",
      ]

    restart: always
    # ports:
    #   - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
    depends_on:
      - pg1

volumes:
  pg1_data:
