name: churhc-dev
on:
  push:
    branches:
      - develop
env:
  SHA: ${{ github.sha }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Django app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            mkdir app 
            cd app 
            git clone git@github.com:walosha/church_be.git 
            echo 'Deployment successful to digital ocean'
